/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.7.0.0 (NJsonSchema v10.1.24.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable()
export class DefaultClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(@Inject(HttpClient) http: HttpClient, @Optional() @Inject(API_BASE_URL) baseUrl?: string) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }

    getAll(): Observable<GenericModel | null> {
        let url_ = this.baseUrl + "/api/Default";
        url_ = url_.replace(/[?&]$/, "");

        let options_ : any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
                "Accept": "application/json"
            })
        };

        return this.http.request("get", url_, options_).pipe(_observableMergeMap((response_ : any) => {
            return this.processGetAll(response_);
        })).pipe(_observableCatch((response_: any) => {
            if (response_ instanceof HttpResponseBase) {
                try {
                    return this.processGetAll(<any>response_);
                } catch (e) {
                    return <Observable<GenericModel | null>><any>_observableThrow(e);
                }
            } else
                return <Observable<GenericModel | null>><any>_observableThrow(response_);
        }));
    }

    protected processGetAll(response: HttpResponseBase): Observable<GenericModel | null> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? GenericModel.fromJS(resultData200) : <any>null;
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<GenericModel | null>(<any>null);
    }
}

export class GenericModel implements IGenericModel {
    filterProfileRequest?: FilterProfileRequest | undefined;
    filterProfileResponse?: FilterProfileResponse | undefined;
    provincialResponse?: ProvincialResponse | undefined;
    districtResponse?: DistrictResponse | undefined;
    communceResponse?: CommunceResponse | undefined;
    profileViewDetailResponse?: ProfileViewDetailResponse | undefined;
    profileViewDetailRequest?: ProfileViewDetailRequest | undefined;
    telesaleRequest?: TelesaleRequest | undefined;
    userNewRequest?: UserNewRequest | undefined;
    userNewResponse?: UserNewResponse | undefined;
    userDetailResponse?: UserDetailResponse | undefined;
    userDisableScopeRequest?: UserDisableScopeRequest | undefined;
    userUpdateRequest?: UserUpdateRequest | undefined;
    userCreateRequest?: UserCreateRequest | undefined;

    constructor(data?: IGenericModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.filterProfileRequest = _data["FilterProfileRequest"] ? FilterProfileRequest.fromJS(_data["FilterProfileRequest"]) : <any>undefined;
            this.filterProfileResponse = _data["FilterProfileResponse"] ? FilterProfileResponse.fromJS(_data["FilterProfileResponse"]) : <any>undefined;
            this.provincialResponse = _data["ProvincialResponse"] ? ProvincialResponse.fromJS(_data["ProvincialResponse"]) : <any>undefined;
            this.districtResponse = _data["DistrictResponse"] ? DistrictResponse.fromJS(_data["DistrictResponse"]) : <any>undefined;
            this.communceResponse = _data["CommunceResponse"] ? CommunceResponse.fromJS(_data["CommunceResponse"]) : <any>undefined;
            this.profileViewDetailResponse = _data["ProfileViewDetailResponse"] ? ProfileViewDetailResponse.fromJS(_data["ProfileViewDetailResponse"]) : <any>undefined;
            this.profileViewDetailRequest = _data["ProfileViewDetailRequest"] ? ProfileViewDetailRequest.fromJS(_data["ProfileViewDetailRequest"]) : <any>undefined;
            this.telesaleRequest = _data["TelesaleRequest"] ? TelesaleRequest.fromJS(_data["TelesaleRequest"]) : <any>undefined;
            this.userNewRequest = _data["UserNewRequest"] ? UserNewRequest.fromJS(_data["UserNewRequest"]) : <any>undefined;
            this.userNewResponse = _data["UserNewResponse"] ? UserNewResponse.fromJS(_data["UserNewResponse"]) : <any>undefined;
            this.userDetailResponse = _data["UserDetailResponse"] ? UserDetailResponse.fromJS(_data["UserDetailResponse"]) : <any>undefined;
            this.userDisableScopeRequest = _data["UserDisableScopeRequest"] ? UserDisableScopeRequest.fromJS(_data["UserDisableScopeRequest"]) : <any>undefined;
            this.userUpdateRequest = _data["UserUpdateRequest"] ? UserUpdateRequest.fromJS(_data["UserUpdateRequest"]) : <any>undefined;
            this.userCreateRequest = _data["UserCreateRequest"] ? UserCreateRequest.fromJS(_data["UserCreateRequest"]) : <any>undefined;
        }
    }

    static fromJS(data: any): GenericModel {
        data = typeof data === 'object' ? data : {};
        let result = new GenericModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["FilterProfileRequest"] = this.filterProfileRequest ? this.filterProfileRequest.toJSON() : <any>undefined;
        data["FilterProfileResponse"] = this.filterProfileResponse ? this.filterProfileResponse.toJSON() : <any>undefined;
        data["ProvincialResponse"] = this.provincialResponse ? this.provincialResponse.toJSON() : <any>undefined;
        data["DistrictResponse"] = this.districtResponse ? this.districtResponse.toJSON() : <any>undefined;
        data["CommunceResponse"] = this.communceResponse ? this.communceResponse.toJSON() : <any>undefined;
        data["ProfileViewDetailResponse"] = this.profileViewDetailResponse ? this.profileViewDetailResponse.toJSON() : <any>undefined;
        data["ProfileViewDetailRequest"] = this.profileViewDetailRequest ? this.profileViewDetailRequest.toJSON() : <any>undefined;
        data["TelesaleRequest"] = this.telesaleRequest ? this.telesaleRequest.toJSON() : <any>undefined;
        data["UserNewRequest"] = this.userNewRequest ? this.userNewRequest.toJSON() : <any>undefined;
        data["UserNewResponse"] = this.userNewResponse ? this.userNewResponse.toJSON() : <any>undefined;
        data["UserDetailResponse"] = this.userDetailResponse ? this.userDetailResponse.toJSON() : <any>undefined;
        data["UserDisableScopeRequest"] = this.userDisableScopeRequest ? this.userDisableScopeRequest.toJSON() : <any>undefined;
        data["UserUpdateRequest"] = this.userUpdateRequest ? this.userUpdateRequest.toJSON() : <any>undefined;
        data["UserCreateRequest"] = this.userCreateRequest ? this.userCreateRequest.toJSON() : <any>undefined;
        return data; 
    }
}

export interface IGenericModel {
    filterProfileRequest?: FilterProfileRequest | undefined;
    filterProfileResponse?: FilterProfileResponse | undefined;
    provincialResponse?: ProvincialResponse | undefined;
    districtResponse?: DistrictResponse | undefined;
    communceResponse?: CommunceResponse | undefined;
    profileViewDetailResponse?: ProfileViewDetailResponse | undefined;
    profileViewDetailRequest?: ProfileViewDetailRequest | undefined;
    telesaleRequest?: TelesaleRequest | undefined;
    userNewRequest?: UserNewRequest | undefined;
    userNewResponse?: UserNewResponse | undefined;
    userDetailResponse?: UserDetailResponse | undefined;
    userDisableScopeRequest?: UserDisableScopeRequest | undefined;
    userUpdateRequest?: UserUpdateRequest | undefined;
    userCreateRequest?: UserCreateRequest | undefined;
}

export class FilterProfileRequest implements IFilterProfileRequest {
    id_number?: string | undefined;
    full_name?: string | undefined;
    phone_number?: string | undefined;
    type_of_loan?: number | undefined;
    product_loan?: string | undefined;
    loan_form?: number | undefined;
    form_payment?: number | undefined;
    type_customer?: number | undefined;
    create_from?: string | undefined;
    create_to?: string | undefined;
    classify_cutomer?: string | undefined;

    constructor(data?: IFilterProfileRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id_number = _data["id_number"];
            this.full_name = _data["full_name"];
            this.phone_number = _data["phone_number"];
            this.type_of_loan = _data["type_of_loan"];
            this.product_loan = _data["product_loan"];
            this.loan_form = _data["loan_form"];
            this.form_payment = _data["form_payment"];
            this.type_customer = _data["type_customer"];
            this.create_from = _data["create_from"];
            this.create_to = _data["create_to"];
            this.classify_cutomer = _data["classify_cutomer"];
        }
    }

    static fromJS(data: any): FilterProfileRequest {
        data = typeof data === 'object' ? data : {};
        let result = new FilterProfileRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id_number"] = this.id_number;
        data["full_name"] = this.full_name;
        data["phone_number"] = this.phone_number;
        data["type_of_loan"] = this.type_of_loan;
        data["product_loan"] = this.product_loan;
        data["loan_form"] = this.loan_form;
        data["form_payment"] = this.form_payment;
        data["type_customer"] = this.type_customer;
        data["create_from"] = this.create_from;
        data["create_to"] = this.create_to;
        data["classify_cutomer"] = this.classify_cutomer;
        return data; 
    }
}

export interface IFilterProfileRequest {
    id_number?: string | undefined;
    full_name?: string | undefined;
    phone_number?: string | undefined;
    type_of_loan?: number | undefined;
    product_loan?: string | undefined;
    loan_form?: number | undefined;
    form_payment?: number | undefined;
    type_customer?: number | undefined;
    create_from?: string | undefined;
    create_to?: string | undefined;
    classify_cutomer?: string | undefined;
}

export class GenericResponse implements IGenericResponse {
    errorCode?: string | undefined;
    errorMessage?: string | undefined;
    role?: string | undefined;

    constructor(data?: IGenericResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.errorCode = _data["errorCode"];
            this.errorMessage = _data["errorMessage"];
            this.role = _data["role"];
        }
    }

    static fromJS(data: any): GenericResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GenericResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["errorCode"] = this.errorCode;
        data["errorMessage"] = this.errorMessage;
        data["role"] = this.role;
        return data; 
    }
}

export interface IGenericResponse {
    errorCode?: string | undefined;
    errorMessage?: string | undefined;
    role?: string | undefined;
}

export class FilterProfileResponse extends GenericResponse implements IFilterProfileResponse {
    list_new_profile?: Profile[] | undefined;
    list_old_profile?: Profile[] | undefined;
    current_page!: number;

    constructor(data?: IFilterProfileResponse) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["list_new_profile"])) {
                this.list_new_profile = [] as any;
                for (let item of _data["list_new_profile"])
                    this.list_new_profile!.push(Profile.fromJS(item));
            }
            if (Array.isArray(_data["list_old_profile"])) {
                this.list_old_profile = [] as any;
                for (let item of _data["list_old_profile"])
                    this.list_old_profile!.push(Profile.fromJS(item));
            }
            this.current_page = _data["current_page"];
        }
    }

    static fromJS(data: any): FilterProfileResponse {
        data = typeof data === 'object' ? data : {};
        let result = new FilterProfileResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.list_new_profile)) {
            data["list_new_profile"] = [];
            for (let item of this.list_new_profile)
                data["list_new_profile"].push(item.toJSON());
        }
        if (Array.isArray(this.list_old_profile)) {
            data["list_old_profile"] = [];
            for (let item of this.list_old_profile)
                data["list_old_profile"].push(item.toJSON());
        }
        data["current_page"] = this.current_page;
        super.toJSON(data);
        return data; 
    }
}

export interface IFilterProfileResponse extends IGenericResponse {
    list_new_profile?: Profile[] | undefined;
    list_old_profile?: Profile[] | undefined;
    current_page: number;
}

export class Profile implements IProfile {
    id_profile?: string | undefined;
    fullname?: string | undefined;
    id_number?: string | undefined;
    scope?: string | undefined;
    status?: string | undefined;

    constructor(data?: IProfile) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id_profile = _data["id_profile"];
            this.fullname = _data["fullname"];
            this.id_number = _data["id_number"];
            this.scope = _data["scope"];
            this.status = _data["status"];
        }
    }

    static fromJS(data: any): Profile {
        data = typeof data === 'object' ? data : {};
        let result = new Profile();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id_profile"] = this.id_profile;
        data["fullname"] = this.fullname;
        data["id_number"] = this.id_number;
        data["scope"] = this.scope;
        data["status"] = this.status;
        return data; 
    }
}

export interface IProfile {
    id_profile?: string | undefined;
    fullname?: string | undefined;
    id_number?: string | undefined;
    scope?: string | undefined;
    status?: string | undefined;
}

export class ProvincialResponse extends GenericResponse implements IProvincialResponse {
    provincial?: Provincial[] | undefined;

    constructor(data?: IProvincialResponse) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["provincial"])) {
                this.provincial = [] as any;
                for (let item of _data["provincial"])
                    this.provincial!.push(Provincial.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ProvincialResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ProvincialResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.provincial)) {
            data["provincial"] = [];
            for (let item of this.provincial)
                data["provincial"].push(item.toJSON());
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IProvincialResponse extends IGenericResponse {
    provincial?: Provincial[] | undefined;
}

export class Provincial implements IProvincial {
    name?: string | undefined;
    slug?: string | undefined;
    type?: string | undefined;
    name_with_type?: string | undefined;
    code?: string | undefined;

    constructor(data?: IProvincial) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.slug = _data["slug"];
            this.type = _data["type"];
            this.name_with_type = _data["name_with_type"];
            this.code = _data["code"];
        }
    }

    static fromJS(data: any): Provincial {
        data = typeof data === 'object' ? data : {};
        let result = new Provincial();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["slug"] = this.slug;
        data["type"] = this.type;
        data["name_with_type"] = this.name_with_type;
        data["code"] = this.code;
        return data; 
    }
}

export interface IProvincial {
    name?: string | undefined;
    slug?: string | undefined;
    type?: string | undefined;
    name_with_type?: string | undefined;
    code?: string | undefined;
}

export class DistrictResponse extends GenericResponse implements IDistrictResponse {
    district?: District[] | undefined;

    constructor(data?: IDistrictResponse) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["district"])) {
                this.district = [] as any;
                for (let item of _data["district"])
                    this.district!.push(District.fromJS(item));
            }
        }
    }

    static fromJS(data: any): DistrictResponse {
        data = typeof data === 'object' ? data : {};
        let result = new DistrictResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.district)) {
            data["district"] = [];
            for (let item of this.district)
                data["district"].push(item.toJSON());
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IDistrictResponse extends IGenericResponse {
    district?: District[] | undefined;
}

export class District implements IDistrict {
    name?: string | undefined;
    slug?: string | undefined;
    type?: string | undefined;
    name_with_type?: string | undefined;
    path_with_type?: string | undefined;
    code?: string | undefined;
    parent_code?: string | undefined;

    constructor(data?: IDistrict) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.slug = _data["slug"];
            this.type = _data["type"];
            this.name_with_type = _data["name_with_type"];
            this.path_with_type = _data["path_with_type"];
            this.code = _data["code"];
            this.parent_code = _data["parent_code"];
        }
    }

    static fromJS(data: any): District {
        data = typeof data === 'object' ? data : {};
        let result = new District();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["slug"] = this.slug;
        data["type"] = this.type;
        data["name_with_type"] = this.name_with_type;
        data["path_with_type"] = this.path_with_type;
        data["code"] = this.code;
        data["parent_code"] = this.parent_code;
        return data; 
    }
}

export interface IDistrict {
    name?: string | undefined;
    slug?: string | undefined;
    type?: string | undefined;
    name_with_type?: string | undefined;
    path_with_type?: string | undefined;
    code?: string | undefined;
    parent_code?: string | undefined;
}

export class CommunceResponse extends GenericResponse implements ICommunceResponse {
    communce?: Communce[] | undefined;

    constructor(data?: ICommunceResponse) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["communce"])) {
                this.communce = [] as any;
                for (let item of _data["communce"])
                    this.communce!.push(Communce.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CommunceResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CommunceResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.communce)) {
            data["communce"] = [];
            for (let item of this.communce)
                data["communce"].push(item.toJSON());
        }
        super.toJSON(data);
        return data; 
    }
}

export interface ICommunceResponse extends IGenericResponse {
    communce?: Communce[] | undefined;
}

export class Communce implements ICommunce {
    name?: string | undefined;
    slug?: string | undefined;
    type?: string | undefined;
    name_with_type?: string | undefined;
    path_with_type?: string | undefined;
    path?: string | undefined;
    code?: string | undefined;
    parent_code?: string | undefined;

    constructor(data?: ICommunce) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.slug = _data["slug"];
            this.type = _data["type"];
            this.name_with_type = _data["name_with_type"];
            this.path_with_type = _data["path_with_type"];
            this.path = _data["path"];
            this.code = _data["code"];
            this.parent_code = _data["parent_code"];
        }
    }

    static fromJS(data: any): Communce {
        data = typeof data === 'object' ? data : {};
        let result = new Communce();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["slug"] = this.slug;
        data["type"] = this.type;
        data["name_with_type"] = this.name_with_type;
        data["path_with_type"] = this.path_with_type;
        data["path"] = this.path;
        data["code"] = this.code;
        data["parent_code"] = this.parent_code;
        return data; 
    }
}

export interface ICommunce {
    name?: string | undefined;
    slug?: string | undefined;
    type?: string | undefined;
    name_with_type?: string | undefined;
    path_with_type?: string | undefined;
    path?: string | undefined;
    code?: string | undefined;
    parent_code?: string | undefined;
}

export class ProfileViewDetailResponse extends GenericResponse implements IProfileViewDetailResponse {
    profile?: BlockField[] | undefined;

    constructor(data?: IProfileViewDetailResponse) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            if (Array.isArray(_data["profile"])) {
                this.profile = [] as any;
                for (let item of _data["profile"])
                    this.profile!.push(BlockField.fromJS(item));
            }
        }
    }

    static fromJS(data: any): ProfileViewDetailResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ProfileViewDetailResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.profile)) {
            data["profile"] = [];
            for (let item of this.profile)
                data["profile"].push(item.toJSON());
        }
        super.toJSON(data);
        return data; 
    }
}

export interface IProfileViewDetailResponse extends IGenericResponse {
    profile?: BlockField[] | undefined;
}

export class BlockField implements IBlockField {
    block_id?: string | undefined;
    block_name?: string | undefined;
    verify_flag?: string | undefined;
    verified?: string | undefined;
    listDoc?: FileDinhKem[] | undefined;
    listFields?: Field[] | undefined;

    constructor(data?: IBlockField) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.block_id = _data["block_id"];
            this.block_name = _data["block_name"];
            this.verify_flag = _data["verify_flag"];
            this.verified = _data["verified"];
            if (Array.isArray(_data["listDoc"])) {
                this.listDoc = [] as any;
                for (let item of _data["listDoc"])
                    this.listDoc!.push(FileDinhKem.fromJS(item));
            }
            if (Array.isArray(_data["listFields"])) {
                this.listFields = [] as any;
                for (let item of _data["listFields"])
                    this.listFields!.push(Field.fromJS(item));
            }
        }
    }

    static fromJS(data: any): BlockField {
        data = typeof data === 'object' ? data : {};
        let result = new BlockField();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["block_id"] = this.block_id;
        data["block_name"] = this.block_name;
        data["verify_flag"] = this.verify_flag;
        data["verified"] = this.verified;
        if (Array.isArray(this.listDoc)) {
            data["listDoc"] = [];
            for (let item of this.listDoc)
                data["listDoc"].push(item.toJSON());
        }
        if (Array.isArray(this.listFields)) {
            data["listFields"] = [];
            for (let item of this.listFields)
                data["listFields"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IBlockField {
    block_id?: string | undefined;
    block_name?: string | undefined;
    verify_flag?: string | undefined;
    verified?: string | undefined;
    listDoc?: FileDinhKem[] | undefined;
    listFields?: Field[] | undefined;
}

export class FileDinhKem implements IFileDinhKem {
    dinh_danh_tai_lieu?: string | undefined;
    dinh_danh_ho_so?: string | undefined;
    dinh_danh_the_loai?: string | undefined;
    nen_tang?: string | undefined;
    thoi_diem_tao?: string | undefined;
    dia_chi?: string | undefined;
    vi_tri?: string | undefined;
    ten_thiet_bi?: string | undefined;
    ghi_chu?: string | undefined;
    ten_file?: string | undefined;

    constructor(data?: IFileDinhKem) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.dinh_danh_tai_lieu = _data["dinh_danh_tai_lieu"];
            this.dinh_danh_ho_so = _data["dinh_danh_ho_so"];
            this.dinh_danh_the_loai = _data["dinh_danh_the_loai"];
            this.nen_tang = _data["nen_tang"];
            this.thoi_diem_tao = _data["thoi_diem_tao"];
            this.dia_chi = _data["dia_chi"];
            this.vi_tri = _data["vi_tri"];
            this.ten_thiet_bi = _data["ten_thiet_bi"];
            this.ghi_chu = _data["ghi_chu"];
            this.ten_file = _data["ten_file"];
        }
    }

    static fromJS(data: any): FileDinhKem {
        data = typeof data === 'object' ? data : {};
        let result = new FileDinhKem();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["dinh_danh_tai_lieu"] = this.dinh_danh_tai_lieu;
        data["dinh_danh_ho_so"] = this.dinh_danh_ho_so;
        data["dinh_danh_the_loai"] = this.dinh_danh_the_loai;
        data["nen_tang"] = this.nen_tang;
        data["thoi_diem_tao"] = this.thoi_diem_tao;
        data["dia_chi"] = this.dia_chi;
        data["vi_tri"] = this.vi_tri;
        data["ten_thiet_bi"] = this.ten_thiet_bi;
        data["ghi_chu"] = this.ghi_chu;
        data["ten_file"] = this.ten_file;
        return data; 
    }
}

export interface IFileDinhKem {
    dinh_danh_tai_lieu?: string | undefined;
    dinh_danh_ho_so?: string | undefined;
    dinh_danh_the_loai?: string | undefined;
    nen_tang?: string | undefined;
    thoi_diem_tao?: string | undefined;
    dia_chi?: string | undefined;
    vi_tri?: string | undefined;
    ten_thiet_bi?: string | undefined;
    ghi_chu?: string | undefined;
    ten_file?: string | undefined;
}

export class Field implements IField {
    name?: string | undefined;
    value?: string | undefined;
    verified?: string | undefined;
    verify_flag?: string | undefined;

    constructor(data?: IField) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.value = _data["value"];
            this.verified = _data["verified"];
            this.verify_flag = _data["verify_flag"];
        }
    }

    static fromJS(data: any): Field {
        data = typeof data === 'object' ? data : {};
        let result = new Field();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["value"] = this.value;
        data["verified"] = this.verified;
        data["verify_flag"] = this.verify_flag;
        return data; 
    }
}

export interface IField {
    name?: string | undefined;
    value?: string | undefined;
    verified?: string | undefined;
    verify_flag?: string | undefined;
}

export class ProfileViewDetailRequest implements IProfileViewDetailRequest {
    id_profile?: string | undefined;
    classify_cutomer?: string | undefined;

    constructor(data?: IProfileViewDetailRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id_profile = _data["id_profile"];
            this.classify_cutomer = _data["classify_cutomer"];
        }
    }

    static fromJS(data: any): ProfileViewDetailRequest {
        data = typeof data === 'object' ? data : {};
        let result = new ProfileViewDetailRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id_profile"] = this.id_profile;
        data["classify_cutomer"] = this.classify_cutomer;
        return data; 
    }
}

export interface IProfileViewDetailRequest {
    id_profile?: string | undefined;
    classify_cutomer?: string | undefined;
}

export class TelesaleRequest implements ITelesaleRequest {
    id_profile?: string | undefined;
    status_profile?: string | undefined;
    scope?: string | undefined;
    list_parameter?: Parameter[] | undefined;
    note?: string | undefined;

    constructor(data?: ITelesaleRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id_profile = _data["id_profile"];
            this.status_profile = _data["status_profile"];
            this.scope = _data["scope"];
            if (Array.isArray(_data["list_parameter"])) {
                this.list_parameter = [] as any;
                for (let item of _data["list_parameter"])
                    this.list_parameter!.push(Parameter.fromJS(item));
            }
            this.note = _data["note"];
        }
    }

    static fromJS(data: any): TelesaleRequest {
        data = typeof data === 'object' ? data : {};
        let result = new TelesaleRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id_profile"] = this.id_profile;
        data["status_profile"] = this.status_profile;
        data["scope"] = this.scope;
        if (Array.isArray(this.list_parameter)) {
            data["list_parameter"] = [];
            for (let item of this.list_parameter)
                data["list_parameter"].push(item.toJSON());
        }
        data["note"] = this.note;
        return data; 
    }
}

export interface ITelesaleRequest {
    id_profile?: string | undefined;
    status_profile?: string | undefined;
    scope?: string | undefined;
    list_parameter?: Parameter[] | undefined;
    note?: string | undefined;
}

export class Parameter implements IParameter {
    block_id?: string | undefined;
    name?: string | undefined;
    value?: string | undefined;

    constructor(data?: IParameter) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.block_id = _data["block_id"];
            this.name = _data["name"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): Parameter {
        data = typeof data === 'object' ? data : {};
        let result = new Parameter();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["block_id"] = this.block_id;
        data["name"] = this.name;
        data["value"] = this.value;
        return data; 
    }
}

export interface IParameter {
    block_id?: string | undefined;
    name?: string | undefined;
    value?: string | undefined;
}

export class UserNewRequest implements IUserNewRequest {
    new_user_id?: string | undefined;
    full_name?: string | undefined;
    origanization?: string | undefined;
    position?: string | undefined;
    phone_number?: string | undefined;
    email?: string | undefined;
    address?: string | undefined;
    role?: string | undefined;
    scope?: string[] | undefined;
    note?: string | undefined;

    constructor(data?: IUserNewRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.new_user_id = _data["new_user_id"];
            this.full_name = _data["full_name"];
            this.origanization = _data["origanization"];
            this.position = _data["position"];
            this.phone_number = _data["phone_number"];
            this.email = _data["email"];
            this.address = _data["address"];
            this.role = _data["role"];
            if (Array.isArray(_data["scope"])) {
                this.scope = [] as any;
                for (let item of _data["scope"])
                    this.scope!.push(item);
            }
            this.note = _data["note"];
        }
    }

    static fromJS(data: any): UserNewRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UserNewRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["new_user_id"] = this.new_user_id;
        data["full_name"] = this.full_name;
        data["origanization"] = this.origanization;
        data["position"] = this.position;
        data["phone_number"] = this.phone_number;
        data["email"] = this.email;
        data["address"] = this.address;
        data["role"] = this.role;
        if (Array.isArray(this.scope)) {
            data["scope"] = [];
            for (let item of this.scope)
                data["scope"].push(item);
        }
        data["note"] = this.note;
        return data; 
    }
}

export interface IUserNewRequest {
    new_user_id?: string | undefined;
    full_name?: string | undefined;
    origanization?: string | undefined;
    position?: string | undefined;
    phone_number?: string | undefined;
    email?: string | undefined;
    address?: string | undefined;
    role?: string | undefined;
    scope?: string[] | undefined;
    note?: string | undefined;
}

export class UserNewResponse extends GenericResponse implements IUserNewResponse {
    secret_key?: string | undefined;

    constructor(data?: IUserNewResponse) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.secret_key = _data["secret_key"];
        }
    }

    static fromJS(data: any): UserNewResponse {
        data = typeof data === 'object' ? data : {};
        let result = new UserNewResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["secret_key"] = this.secret_key;
        super.toJSON(data);
        return data; 
    }
}

export interface IUserNewResponse extends IGenericResponse {
    secret_key?: string | undefined;
}

export class UserDetailResponse extends GenericResponse implements IUserDetailResponse {
    user?: User | undefined;

    constructor(data?: IUserDetailResponse) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.user = _data["user"] ? User.fromJS(_data["user"]) : <any>undefined;
        }
    }

    static fromJS(data: any): UserDetailResponse {
        data = typeof data === 'object' ? data : {};
        let result = new UserDetailResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["user"] = this.user ? this.user.toJSON() : <any>undefined;
        super.toJSON(data);
        return data; 
    }
}

export interface IUserDetailResponse extends IGenericResponse {
    user?: User | undefined;
}

export class User implements IUser {
    full_name?: string | undefined;
    user_id?: string | undefined;
    role?: string | undefined;
    status?: string | undefined;
    organization?: string | undefined;
    position?: string | undefined;
    description?: string | undefined;
    phone_number?: string | undefined;
    pass?: string | undefined;
    phone?: string | undefined;
    email?: string | undefined;
    address?: string | undefined;
    create_time?: string | undefined;
    last_time?: string | undefined;
    note?: string | undefined;
    scope?: UserScope[] | undefined;

    constructor(data?: IUser) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.full_name = _data["full_name"];
            this.user_id = _data["user_id"];
            this.role = _data["role"];
            this.status = _data["status"];
            this.organization = _data["organization"];
            this.position = _data["position"];
            this.description = _data["description"];
            this.phone_number = _data["phone_number"];
            this.pass = _data["pass"];
            this.phone = _data["phone"];
            this.email = _data["email"];
            this.address = _data["address"];
            this.create_time = _data["create_time"];
            this.last_time = _data["last_time"];
            this.note = _data["note"];
            if (Array.isArray(_data["scope"])) {
                this.scope = [] as any;
                for (let item of _data["scope"])
                    this.scope!.push(UserScope.fromJS(item));
            }
        }
    }

    static fromJS(data: any): User {
        data = typeof data === 'object' ? data : {};
        let result = new User();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["full_name"] = this.full_name;
        data["user_id"] = this.user_id;
        data["role"] = this.role;
        data["status"] = this.status;
        data["organization"] = this.organization;
        data["position"] = this.position;
        data["description"] = this.description;
        data["phone_number"] = this.phone_number;
        data["pass"] = this.pass;
        data["phone"] = this.phone;
        data["email"] = this.email;
        data["address"] = this.address;
        data["create_time"] = this.create_time;
        data["last_time"] = this.last_time;
        data["note"] = this.note;
        if (Array.isArray(this.scope)) {
            data["scope"] = [];
            for (let item of this.scope)
                data["scope"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IUser {
    full_name?: string | undefined;
    user_id?: string | undefined;
    role?: string | undefined;
    status?: string | undefined;
    organization?: string | undefined;
    position?: string | undefined;
    description?: string | undefined;
    phone_number?: string | undefined;
    pass?: string | undefined;
    phone?: string | undefined;
    email?: string | undefined;
    address?: string | undefined;
    create_time?: string | undefined;
    last_time?: string | undefined;
    note?: string | undefined;
    scope?: UserScope[] | undefined;
}

export class UserScope implements IUserScope {
    scope?: string | undefined;
    from?: string | undefined;
    to?: string | undefined;

    constructor(data?: IUserScope) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.scope = _data["scope"];
            this.from = _data["from"];
            this.to = _data["to"];
        }
    }

    static fromJS(data: any): UserScope {
        data = typeof data === 'object' ? data : {};
        let result = new UserScope();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["scope"] = this.scope;
        data["from"] = this.from;
        data["to"] = this.to;
        return data; 
    }
}

export interface IUserScope {
    scope?: string | undefined;
    from?: string | undefined;
    to?: string | undefined;
}

export class UserDisableScopeRequest implements IUserDisableScopeRequest {
    dis_user_id?: string | undefined;
    scope?: string | undefined;

    constructor(data?: IUserDisableScopeRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.dis_user_id = _data["dis_user_id"];
            this.scope = _data["scope"];
        }
    }

    static fromJS(data: any): UserDisableScopeRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UserDisableScopeRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["dis_user_id"] = this.dis_user_id;
        data["scope"] = this.scope;
        return data; 
    }
}

export interface IUserDisableScopeRequest {
    dis_user_id?: string | undefined;
    scope?: string | undefined;
}

export class UserUpdateRequest implements IUserUpdateRequest {
    update_user_id?: string | undefined;
    full_name?: string | undefined;
    origanization?: string | undefined;
    position?: string | undefined;
    phone_number?: string | undefined;
    email?: string | undefined;
    address?: string | undefined;
    note?: string | undefined;

    constructor(data?: IUserUpdateRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.update_user_id = _data["update_user_id"];
            this.full_name = _data["full_name"];
            this.origanization = _data["origanization"];
            this.position = _data["position"];
            this.phone_number = _data["phone_number"];
            this.email = _data["email"];
            this.address = _data["address"];
            this.note = _data["note"];
        }
    }

    static fromJS(data: any): UserUpdateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UserUpdateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["update_user_id"] = this.update_user_id;
        data["full_name"] = this.full_name;
        data["origanization"] = this.origanization;
        data["position"] = this.position;
        data["phone_number"] = this.phone_number;
        data["email"] = this.email;
        data["address"] = this.address;
        data["note"] = this.note;
        return data; 
    }
}

export interface IUserUpdateRequest {
    update_user_id?: string | undefined;
    full_name?: string | undefined;
    origanization?: string | undefined;
    position?: string | undefined;
    phone_number?: string | undefined;
    email?: string | undefined;
    address?: string | undefined;
    note?: string | undefined;
}

export class UserCreateRequest implements IUserCreateRequest {
    new_user_id?: string | undefined;
    full_name?: string | undefined;
    origanization?: string | undefined;
    position?: string | undefined;
    phone_number?: string | undefined;
    email?: string | undefined;
    address?: string | undefined;
    role?: string | undefined;
    note?: string | undefined;
    scope?: UserScopeRequest[] | undefined;

    constructor(data?: IUserCreateRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.new_user_id = _data["new_user_id"];
            this.full_name = _data["full_name"];
            this.origanization = _data["origanization"];
            this.position = _data["position"];
            this.phone_number = _data["phone_number"];
            this.email = _data["email"];
            this.address = _data["address"];
            this.role = _data["role"];
            this.note = _data["note"];
            if (Array.isArray(_data["scope"])) {
                this.scope = [] as any;
                for (let item of _data["scope"])
                    this.scope!.push(UserScopeRequest.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UserCreateRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UserCreateRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["new_user_id"] = this.new_user_id;
        data["full_name"] = this.full_name;
        data["origanization"] = this.origanization;
        data["position"] = this.position;
        data["phone_number"] = this.phone_number;
        data["email"] = this.email;
        data["address"] = this.address;
        data["role"] = this.role;
        data["note"] = this.note;
        if (Array.isArray(this.scope)) {
            data["scope"] = [];
            for (let item of this.scope)
                data["scope"].push(item.toJSON());
        }
        return data; 
    }
}

export interface IUserCreateRequest {
    new_user_id?: string | undefined;
    full_name?: string | undefined;
    origanization?: string | undefined;
    position?: string | undefined;
    phone_number?: string | undefined;
    email?: string | undefined;
    address?: string | undefined;
    role?: string | undefined;
    note?: string | undefined;
    scope?: UserScopeRequest[] | undefined;
}

export class UserScopeRequest implements IUserScopeRequest {
    scope?: string | undefined;
    start_date?: string | undefined;
    exp_date?: string | undefined;

    constructor(data?: IUserScopeRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.scope = _data["scope"];
            this.start_date = _data["start_date"];
            this.exp_date = _data["exp_date"];
        }
    }

    static fromJS(data: any): UserScopeRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UserScopeRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["scope"] = this.scope;
        data["start_date"] = this.start_date;
        data["exp_date"] = this.exp_date;
        return data; 
    }
}

export interface IUserScopeRequest {
    scope?: string | undefined;
    start_date?: string | undefined;
    exp_date?: string | undefined;
}

export class SwaggerException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}