/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.7.0.0 (NJsonSchema v10.1.24.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming


import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf, from, generate } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken, Injector } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';
import { environment } from '../../environments/environment';
import { AuthService } from '../services/auth.service';
import { SHA256 } from '../common/functions';
import { FilterProfileRequest, ProfileViewDetailRequest, SwaggerException, TelesaleRequest } from '../common/model/generic-model';


export const API_BASE_URL = new InjectionToken<string>
    ('API URL', {
        providedIn: 'root',
        factory: () => environment.apiUrlProfile
    });
@Injectable({
    providedIn: 'root'
})
export class ProfileClient {
    private http: HttpClient;
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(
        private authService: AuthService,
        @Inject(HttpClient) http: HttpClient,
        @Optional() @Inject(API_BASE_URL) baseUrl?: string,
    ) {
        this.http = http;
        this.baseUrl = baseUrl ? baseUrl : "";
    }


    public filterProfile(page: number, request: FilterProfileRequest, fid: string = 'F15'): Observable<any> {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/filter/{page}?";
        url_ = url_.replace("{page}", encodeURIComponent("" + page));
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "fid=" + encodeURIComponent("" + fid) + "&";
        params.push(fid);
        const keyParams: string[] = [
            'id_number',
            'full_name',
            'phone_number',
            'type_of_loan',
            'product_loan',
            'loan_form',
            'form_payment',
            'type_customer',
            'create_from',
            'create_to',
            'classify_cutomer'
        ];
        for (const key of keyParams) {
            const v = request[key] ?? '';
            if (v !== '') {
                url_ += `${key}=` + encodeURIComponent("" + v) + "&";

            } else {
                url_ += `${key}&`;
            }
            params.push(v);
        }
        params.push(String(page));
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params)) + "&";
        url_ = url_.replace(/[?&]$/, "");
        return this.callAPI(url_);
    }


    public telesale(request: TelesaleRequest, fid: string = 'F14') {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/telesale?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "fid=" + encodeURIComponent("" + fid) + "&";
        params.push(fid);
        const keyParams: string[] = [
            'id_profile',
            'status_profile',
            'scope',
            'list_parameter',
            'note'
        ];
        for (const key of keyParams) {
            const v = request[key] ?? '';
            if (v !== '') {
                if (typeof v === 'object') {
                    url_ += `${key}=` + encodeURIComponent("" + JSON.stringify(v)) + "&";
                    params.push(JSON.stringify(v));
                } else {
                    url_ += `${key}=` + encodeURIComponent("" + v) + "&";
                    params.push(v);
                }
            } else {
                url_ += `${key}&`;
                params.push(v);
            }
        }
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params)) + "&";
        url_ = url_.replace(/[?&]$/, "");
        return this.callAPI(url_);
    }

    public viewDetail(request: ProfileViewDetailRequest, fid: string = 'F16') {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/view_detail?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "fid=" + encodeURIComponent("" + fid) + "&";
        params.push(fid);
        const keyParams: string[] = [
            'id_profile',
            'classify_cutomer'
        ];
        for (const key of keyParams) {
            const v = request[key] ?? '';
            if (v !== '') {
                url_ += `${key}=` + encodeURIComponent("" + v) + "&";

            } else {
                url_ += `${key}&`;
            }
            params.push(v);
        }
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params)) + "&";
        url_ = url_.replace(/[?&]$/, "");
        return this.callAPI(url_);
    }

    public viewDoc(id_profile: string, doc_id: string, fid: string = 'F16') {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/view_doc/{doc_id}?";
        url_ = url_.replace("{doc_id}", encodeURIComponent("" + doc_id));
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "fid=" + encodeURIComponent("" + fid) + "&";
        params.push(fid);
        url_ += "id_profile=" + encodeURIComponent("" + id_profile) + "&";
        params.push(id_profile);
        // url_ += "doc_id=" + encodeURIComponent("" + doc_id) + "&";
        params.push(doc_id);
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params));

        url_ = url_.replace(/[?&]$/, "");
        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };
        return this.http.request('get', url_, options_)
        // .pipe(_observableMergeMap((response$: any) => {
        //     return this.processResponse(response$);
        // })).pipe(_observableCatch((response$: any) => {
        //     if (response$ instanceof HttpResponseBase) {
        //         try {
        //             return this.processResponse(<any>response$);
        //         } catch (e) {
        //             return <Observable<any | null>><any>_observableThrow(e);
        //         }
        //     } else
        //         return <Observable<any | null>><any>_observableThrow(response$);
        // }));
    }

    public verifyGroupField(id_profile: string, block_id: string, fid: string = 'F32') {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/view_detail/image_portrait?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "fid=" + encodeURIComponent("" + fid) + "&";
        params.push(fid);
        url_ += "id_profile=" + encodeURIComponent("" + id_profile) + "&";
        params.push(id_profile);
        url_ += "block_id=" + encodeURIComponent("" + block_id) + "&";
        params.push(block_id);
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params));

        url_ = url_.replace(/[?&]$/, "");
        return this.callAPI(url_);

    }
    public verifyFieldProfile(id_profile: string, field_name: string, fid: string = 'F33') {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/view_detail/verify_field_profile?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "fid=" + encodeURIComponent("" + fid) + "&";
        params.push(fid);
        url_ += "id_profile=" + encodeURIComponent("" + id_profile) + "&";
        params.push(id_profile);
        url_ += "field_name=" + encodeURIComponent("" + field_name) + "&";
        params.push(field_name);
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params));
        url_ = url_.replace(/[?&]$/, "");
        return this.callAPI(url_);
    }
    public classCustomer(id_profile: string, type_customer: string, fid: string = 'F34') {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/view_detail/class_customer?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "fid=" + encodeURIComponent("" + fid) + "&";
        params.push(fid);
        url_ += "id_profile=" + encodeURIComponent("" + id_profile) + "&";
        params.push(id_profile);
        url_ += "field_name=" + encodeURIComponent("" + type_customer) + "&";
        params.push(type_customer);
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params));
        url_ = url_.replace(/[?&]$/, "");
        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };
        return this.callAPI(url_);
    }

    public creditScoringProfile(id_profile: string, fid: string = 'F35') {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/credit_scoring_profile?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "fid=" + encodeURIComponent("" + fid) + "&";
        params.push(fid);
        url_ += "id_profile=" + encodeURIComponent("" + id_profile) + "&";
        params.push(id_profile);
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params));
        url_ = url_.replace(/[?&]$/, "");
        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };
        return this.callAPI(url_);
    }

    public verifyFinishProfile(id_profile: string, status_profile: string, note_his_profile: string, fid: string = 'F36') {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/verify_finish_profile?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "fid=" + encodeURIComponent("" + fid) + "&";
        params.push(fid);
        url_ += "id_profile=" + encodeURIComponent("" + id_profile) + "&";
        params.push(id_profile);
        url_ += "status_profile=" + encodeURIComponent("" + status_profile) + "&";
        params.push(status_profile);
        url_ += "note_his_profile=" + encodeURIComponent("" + note_his_profile) + "&";
        params.push(note_his_profile);
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params));
        url_ = url_.replace(/[?&]$/, "");
        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };
        return this.callAPI(url_);
    }
    public cancellProfile(list_id_profile: string[], note_his_profile: string, fid: string = 'F25') {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/verify_finish_profile?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "fid=" + encodeURIComponent("" + fid) + "&";
        params.push(fid);
        url_ += "list_id_profile=" + encodeURIComponent("" + JSON.stringify(list_id_profile)) + "&";
        params.push(JSON.stringify(list_id_profile));
        url_ += "note_his_profile=" + encodeURIComponent("" + note_his_profile) + "&";
        params.push(note_his_profile);
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params));
        url_ = url_.replace(/[?&]$/, "");
        return this.callAPI(url_);
    }

    public imagePortait(id_profile: string, fid: string = 'F16') {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/view_detail/image_portrait?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "fid=" + encodeURIComponent("" + fid) + "&";
        params.push(fid);
        url_ += "id_profile=" + encodeURIComponent("" + id_profile) + "&";
        params.push(id_profile);
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params));

        url_ = url_.replace(/[?&]$/, "");
        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({
            })
        };
        return this.http.request('get', url_, options_);
    }

    public approvalFinishProfile(id_profile: string, status_profile: string, note_his_profile: string, fid: string = 'F1A') {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/approval_finish_profile?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "fid=" + encodeURIComponent("" + fid) + "&";
        params.push(fid);
        url_ += "id_profile=" + encodeURIComponent("" + id_profile) + "&";
        params.push(id_profile);
        url_ += "status_profile=" + encodeURIComponent("" + status_profile) + "&";
        params.push(status_profile);
        url_ += "note_his_profile=" + encodeURIComponent("" + note_his_profile) + "&";
        params.push(note_his_profile);
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params));

        url_ = url_.replace(/[?&]$/, "");
        return this.callAPI(url_);
    }

    public getProvincial() {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/provincial?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params)) + "&";
        url_ = url_.replace(/[?&]$/, "");
        return this.callAPI(url_);
    }

    public getDistrict(code_provincial: string) {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/district?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        if (code_provincial) {
            url_ += "code_provincial=" + encodeURIComponent("" + code_provincial) + "&";
            params.push(code_provincial);
        }
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params)) + "&";
        url_ = url_.replace(/[?&]$/, "");
        return this.callAPI(url_);
    }

    public getCommune(code_district: string) {
        let params: string[] = [];
        let url_ = this.baseUrl + "/ipcms/icp/commune?";
        const userId = this.authService.getUserId();
        url_ += "user_id=" + encodeURIComponent("" + userId) + "&";
        params.push(userId);
        params.push(this.authService.getSecretKey());
        if (code_district) {
            url_ += "code_district=" + encodeURIComponent("" + code_district) + "&";
            params.push(code_district);
        }
        url_ += "secret_token=" + encodeURIComponent("" + SHA256(...params)) + "&";
        url_ = url_.replace(/[?&]$/, "");
        return this.callAPI(url_);
    }
    private callAPI(url_: string) {
        let options_: any = {
            observe: "response",
            responseType: "blob",
            headers: new HttpHeaders({})
        };
        return this.http.request('get', url_, options_)
            .pipe(_observableMergeMap((response$: any) => {
                return this.processResponse(response$);
            })).pipe(_observableCatch((response$: any) => {
                if (response$ instanceof HttpResponseBase) {
                    try {
                        return this.processResponse(<any>response$);
                    } catch (e) {
                        return <Observable<any | null>><any>_observableThrow(e);
                    }
                }
                else
                    return <Observable<any | null>><any>_observableThrow(response$);
            }));
    }
    private processResponse(response: HttpResponseBase): Observable<any> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
                (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); } }
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
                let result200: any = null;
                let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 ? resultData200 : <any>null;
                return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<any | null>(<any>null);
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): Observable<any> {
    if (result !== null && result !== undefined)
        return _observableThrow(result);
    else
        return _observableThrow(new SwaggerException(message, status, response, headers, null));
}

function blobToText(blob: any): Observable<string> {
    return new Observable<string>((observer: any) => {
        if (!blob) {
            observer.next("");
            observer.complete();
        } else {
            let reader = new FileReader();
            reader.onload = event => {
                observer.next((<any>event.target).result);
                observer.complete();
            };
            reader.readAsText(blob);
        }
    });
}