export const StatusProfileConstant = {
    MOI: '0',
    DANG_TELESALE: '1',
    CHOT: '2',
    KHACH_HANG_TU_CHOI: '3',
    HUY: '4',
    DANG_HOAN_THIEN: '5',
    DA_HOAN_THIEN: '6',
    LUU_TRU: '7',
    DA_PHE_DUYET_HOAN_THIEN: '8',
    DANG_THAM_DINH: '9',
    DA_THAM_DINH_DAT: '10',
    THAM_DINH_KHONG_DAT: '11',
    DA_PHE_DUYET: '12',
    KHONG_DUOC_PHE_DUYET: '13',
    DA_GIAI_NGAN: '14',
    KHONG_GIAI_NGAN: '15',
    DA_TAT_TOAN: '16',
    NHOM_NO_1: '17',
    NHOM_NO_2: '18',
    NHOM_NO_3: '19',
    NHOM_NO_4: '20',
    NHOM_NO_5: '21',
};
